### ISSUE TITLE
app build issue with cuda and conda

### ISSUE THREAD

**Issue by datacrud8** [photomz/BabyDoctor#1]
### Question

thanks for sharing this project, I am trying to build this project and its completed till the below commant.
Run conda env create -f BabyDoctor/llmenv.yaml

after that "conda activate llmforbio" is throwing error like llmforbio env not available, actually its not creating this env, chceked in conda path as well.

Then this part of the comment also failed with : 
Run MAX_JOBS=8 python3 -m pip install flash-attn

error like : 
Using cached flash_attn-1.0.5.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/lib/nvidia-cuda-toolkit/bin'

actually its running and can see the versions 11.5

so Is that possible to provide pip install requirements.txt version to build this ?
also what version of cuda are you using? if possible please provide detailed step instruction.

**Comment by datacrud8** [comment]
I have successfully installed CUDA on my CPU machine but still ist not working.
Do we need to NVIDIA GPU machine to run this? kindly confirm the details.

**Comment by photomz** [comment]
CUDA is a low-level language for Nvidia GPUs, so yes; you must rent a 1xA10 GPU at least to run this inference.

I suggest you use hosted GPU clouds (Lambda Labs, GCP, AWS, Azure) to alleviate your CUDA config pains.

Closing as this is a local setup issue, unrelated to the repo's base code. Unfortunately, CUDA config is brittle and capricious, but I can't provide customer support.
